package com.university.entities;
// Generated 18 juil. 2018 08:25:27 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Anneeuniversitaire generated by hbm2java
 */
@Entity
@Table(name="anneeuniversitaire"
    ,schema="public"
)
public class Anneeuniversitaire  implements java.io.Serializable {


     private int idanneeuniversitaire;
     private String anneeuniversitaire;
     private String etat;
     private String usercreate;
     private String userlastupdate;
     private String userdelete;

    public Anneeuniversitaire() {
    }

	
    public Anneeuniversitaire(int idanneeuniversitaire) {
        this.idanneeuniversitaire = idanneeuniversitaire;
    }
    public Anneeuniversitaire(int idanneeuniversitaire, String anneeuniversitaire, String etat, String usercreate, String userlastupdate, String userdelete) {
       this.idanneeuniversitaire = idanneeuniversitaire;
       this.anneeuniversitaire = anneeuniversitaire;
       this.etat = etat;
       this.usercreate = usercreate;
       this.userlastupdate = userlastupdate;
       this.userdelete = userdelete;
    }
   
     @Id 

    
    @Column(name="idanneeuniversitaire", unique=true, nullable=false)
    public int getIdanneeuniversitaire() {
        return this.idanneeuniversitaire;
    }
    
    public void setIdanneeuniversitaire(int idanneeuniversitaire) {
        this.idanneeuniversitaire = idanneeuniversitaire;
    }

    
    @Column(name="anneeuniversitaire", length=20)
    public String getAnneeuniversitaire() {
        return this.anneeuniversitaire;
    }
    
    public void setAnneeuniversitaire(String anneeuniversitaire) {
        this.anneeuniversitaire = anneeuniversitaire;
    }

    
    @Column(name="etat", length=20)
    public String getEtat() {
        return this.etat;
    }
    
    public void setEtat(String etat) {
        this.etat = etat;
    }

    
    @Column(name="usercreate", length=50)
    public String getUsercreate() {
        return this.usercreate;
    }
    
    public void setUsercreate(String usercreate) {
        this.usercreate = usercreate;
    }

    
    @Column(name="userlastupdate", length=50)
    public String getUserlastupdate() {
        return this.userlastupdate;
    }
    
    public void setUserlastupdate(String userlastupdate) {
        this.userlastupdate = userlastupdate;
    }

    
    @Column(name="userdelete", length=50)
    public String getUserdelete() {
        return this.userdelete;
    }
    
    public void setUserdelete(String userdelete) {
        this.userdelete = userdelete;
    }




}


