package com.university.entities;
// Generated 18 juil. 2018 08:25:27 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Classe generated by hbm2java
 */
@Entity
@Table(name="classe"
    ,schema="public"
)
public class Classe  implements java.io.Serializable {


     private int idclasse;
     private Filiere filiere;
     private String libelleclasse;
     private BigDecimal scolarite;
     private String usrcreate;
     private String userlastupdate;
     private String userdelete;
     private Set<Enseignantmatiereclasse> enseignantmatiereclasses = new HashSet<Enseignantmatiereclasse>(0);
     private Set<Inscription> inscriptions = new HashSet<Inscription>(0);

    public Classe() {
    }

	
    public Classe(int idclasse) {
        this.idclasse = idclasse;
    }
    public Classe(int idclasse, Filiere filiere, String libelleclasse, BigDecimal scolarite, String usrcreate, String userlastupdate, String userdelete, Set<Enseignantmatiereclasse> enseignantmatiereclasses, Set<Inscription> inscriptions) {
       this.idclasse = idclasse;
       this.filiere = filiere;
       this.libelleclasse = libelleclasse;
       this.scolarite = scolarite;
       this.usrcreate = usrcreate;
       this.userlastupdate = userlastupdate;
       this.userdelete = userdelete;
       this.enseignantmatiereclasses = enseignantmatiereclasses;
       this.inscriptions = inscriptions;
    }
   
     @Id 

    
    @Column(name="idclasse", unique=true, nullable=false)
    public int getIdclasse() {
        return this.idclasse;
    }
    
    public void setIdclasse(int idclasse) {
        this.idclasse = idclasse;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idfiliere")
    public Filiere getFiliere() {
        return this.filiere;
    }
    
    public void setFiliere(Filiere filiere) {
        this.filiere = filiere;
    }

    
    @Column(name="libelleclasse", length=50)
    public String getLibelleclasse() {
        return this.libelleclasse;
    }
    
    public void setLibelleclasse(String libelleclasse) {
        this.libelleclasse = libelleclasse;
    }

    
    @Column(name="scolarite", precision=131089, scale=0)
    public BigDecimal getScolarite() {
        return this.scolarite;
    }
    
    public void setScolarite(BigDecimal scolarite) {
        this.scolarite = scolarite;
    }

    
    @Column(name="usrcreate", length=50)
    public String getUsrcreate() {
        return this.usrcreate;
    }
    
    public void setUsrcreate(String usrcreate) {
        this.usrcreate = usrcreate;
    }

    
    @Column(name="userlastupdate", length=50)
    public String getUserlastupdate() {
        return this.userlastupdate;
    }
    
    public void setUserlastupdate(String userlastupdate) {
        this.userlastupdate = userlastupdate;
    }

    
    @Column(name="userdelete", length=50)
    public String getUserdelete() {
        return this.userdelete;
    }
    
    public void setUserdelete(String userdelete) {
        this.userdelete = userdelete;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="classe")
    public Set<Enseignantmatiereclasse> getEnseignantmatiereclasses() {
        return this.enseignantmatiereclasses;
    }
    
    public void setEnseignantmatiereclasses(Set<Enseignantmatiereclasse> enseignantmatiereclasses) {
        this.enseignantmatiereclasses = enseignantmatiereclasses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="classe")
    public Set<Inscription> getInscriptions() {
        return this.inscriptions;
    }
    
    public void setInscriptions(Set<Inscription> inscriptions) {
        this.inscriptions = inscriptions;
    }




}


