package com.university.entities;
// Generated 18 juil. 2018 08:25:27 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Detailpaiement generated by hbm2java
 */
@Entity
@Table(name="detailpaiement"
    ,schema="public"
)
public class Detailpaiement  implements java.io.Serializable {


     private int iddetailpaiement;
     private Inscription inscription;
     private BigDecimal montantpaye;
     private Date datepaiement;
     private String usercreate;
     private String userlastupdate;
     private String userdelete;
     private String etat;

    public Detailpaiement() {
    }

	
    public Detailpaiement(int iddetailpaiement) {
        this.iddetailpaiement = iddetailpaiement;
    }
    public Detailpaiement(int iddetailpaiement, Inscription inscription, BigDecimal montantpaye, Date datepaiement, String usercreate, String userlastupdate, String userdelete, String etat) {
       this.iddetailpaiement = iddetailpaiement;
       this.inscription = inscription;
       this.montantpaye = montantpaye;
       this.datepaiement = datepaiement;
       this.usercreate = usercreate;
       this.userlastupdate = userlastupdate;
       this.userdelete = userdelete;
       this.etat = etat;
    }
   
     @Id 

    
    @Column(name="iddetailpaiement", unique=true, nullable=false)
    public int getIddetailpaiement() {
        return this.iddetailpaiement;
    }
    
    public void setIddetailpaiement(int iddetailpaiement) {
        this.iddetailpaiement = iddetailpaiement;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idinscription")
    public Inscription getInscription() {
        return this.inscription;
    }
    
    public void setInscription(Inscription inscription) {
        this.inscription = inscription;
    }

    
    @Column(name="montantpaye", precision=131089, scale=0)
    public BigDecimal getMontantpaye() {
        return this.montantpaye;
    }
    
    public void setMontantpaye(BigDecimal montantpaye) {
        this.montantpaye = montantpaye;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="datepaiement", length=13)
    public Date getDatepaiement() {
        return this.datepaiement;
    }
    
    public void setDatepaiement(Date datepaiement) {
        this.datepaiement = datepaiement;
    }

    
    @Column(name="usercreate", length=50)
    public String getUsercreate() {
        return this.usercreate;
    }
    
    public void setUsercreate(String usercreate) {
        this.usercreate = usercreate;
    }

    
    @Column(name="userlastupdate", length=50)
    public String getUserlastupdate() {
        return this.userlastupdate;
    }
    
    public void setUserlastupdate(String userlastupdate) {
        this.userlastupdate = userlastupdate;
    }

    
    @Column(name="userdelete", length=50)
    public String getUserdelete() {
        return this.userdelete;
    }
    
    public void setUserdelete(String userdelete) {
        this.userdelete = userdelete;
    }

    
    @Column(name="etat", length=20)
    public String getEtat() {
        return this.etat;
    }
    
    public void setEtat(String etat) {
        this.etat = etat;
    }




}


