package com.university.entities;
// Generated 18 juil. 2018 08:25:27 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Enseignantmatiereclasse generated by hbm2java
 */
@Entity
@Table(name="enseignantmatiereclasse"
    ,schema="public"
)
public class Enseignantmatiereclasse  implements java.io.Serializable {


     private int idenseignantmatiereclasse;
     private Classe classe;
     private Enseignant enseignant;
     private Matiere matiere;
     private Semestre semestre;
     private Uniteenseignement uniteenseignement;
     private Integer credit;
     private String annee;
     private String usrcreate;
     private String userlastupdate;
     private String userdelete;

    public Enseignantmatiereclasse() {
    }

	
    public Enseignantmatiereclasse(int idenseignantmatiereclasse) {
        this.idenseignantmatiereclasse = idenseignantmatiereclasse;
    }
    public Enseignantmatiereclasse(int idenseignantmatiereclasse, Classe classe, Enseignant enseignant, Matiere matiere, Semestre semestre, Uniteenseignement uniteenseignement, Integer credit, String annee, String usrcreate, String userlastupdate, String userdelete) {
       this.idenseignantmatiereclasse = idenseignantmatiereclasse;
       this.classe = classe;
       this.enseignant = enseignant;
       this.matiere = matiere;
       this.semestre = semestre;
       this.uniteenseignement = uniteenseignement;
       this.credit = credit;
       this.annee = annee;
       this.usrcreate = usrcreate;
       this.userlastupdate = userlastupdate;
       this.userdelete = userdelete;
    }
   
     @Id 

    
    @Column(name="idenseignantmatiereclasse", unique=true, nullable=false)
    public int getIdenseignantmatiereclasse() {
        return this.idenseignantmatiereclasse;
    }
    
    public void setIdenseignantmatiereclasse(int idenseignantmatiereclasse) {
        this.idenseignantmatiereclasse = idenseignantmatiereclasse;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idclasse")
    public Classe getClasse() {
        return this.classe;
    }
    
    public void setClasse(Classe classe) {
        this.classe = classe;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idenseignant")
    public Enseignant getEnseignant() {
        return this.enseignant;
    }
    
    public void setEnseignant(Enseignant enseignant) {
        this.enseignant = enseignant;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idmatiere")
    public Matiere getMatiere() {
        return this.matiere;
    }
    
    public void setMatiere(Matiere matiere) {
        this.matiere = matiere;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idsemestre")
    public Semestre getSemestre() {
        return this.semestre;
    }
    
    public void setSemestre(Semestre semestre) {
        this.semestre = semestre;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idue")
    public Uniteenseignement getUniteenseignement() {
        return this.uniteenseignement;
    }
    
    public void setUniteenseignement(Uniteenseignement uniteenseignement) {
        this.uniteenseignement = uniteenseignement;
    }

    
    @Column(name="credit")
    public Integer getCredit() {
        return this.credit;
    }
    
    public void setCredit(Integer credit) {
        this.credit = credit;
    }

    
    @Column(name="annee", length=20)
    public String getAnnee() {
        return this.annee;
    }
    
    public void setAnnee(String annee) {
        this.annee = annee;
    }

    
    @Column(name="usrcreate", length=50)
    public String getUsrcreate() {
        return this.usrcreate;
    }
    
    public void setUsrcreate(String usrcreate) {
        this.usrcreate = usrcreate;
    }

    
    @Column(name="userlastupdate", length=50)
    public String getUserlastupdate() {
        return this.userlastupdate;
    }
    
    public void setUserlastupdate(String userlastupdate) {
        this.userlastupdate = userlastupdate;
    }

    
    @Column(name="userdelete", length=50)
    public String getUserdelete() {
        return this.userdelete;
    }
    
    public void setUserdelete(String userdelete) {
        this.userdelete = userdelete;
    }




}


