package com.university.entities;
// Generated 18 juil. 2018 08:25:27 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Enseignant generated by hbm2java
 */
@Entity
@Table(name="enseignant"
    ,schema="public"
)
public class Enseignant  implements java.io.Serializable {


     private int idenseignant;
     private String nom;
     private String prenom;
     private String rang;
     private String civilite;
     private String diplome;
     private String etat;
     private String usrcreate;
     private String userlastupdate;
     private String userdelete;
     private Set<Enseignantmatiereclasse> enseignantmatiereclasses = new HashSet<Enseignantmatiereclasse>(0);

    public Enseignant() {
    }

	
    public Enseignant(int idenseignant) {
        this.idenseignant = idenseignant;
    }
    public Enseignant(int idenseignant, String nom, String prenom, String rang, String civilite, String diplome, String etat, String usrcreate, String userlastupdate, String userdelete, Set<Enseignantmatiereclasse> enseignantmatiereclasses) {
       this.idenseignant = idenseignant;
       this.nom = nom;
       this.prenom = prenom;
       this.rang = rang;
       this.civilite = civilite;
       this.diplome = diplome;
       this.etat = etat;
       this.usrcreate = usrcreate;
       this.userlastupdate = userlastupdate;
       this.userdelete = userdelete;
       this.enseignantmatiereclasses = enseignantmatiereclasses;
    }
   
     @Id 

    
    @Column(name="idenseignant", unique=true, nullable=false)
    public int getIdenseignant() {
        return this.idenseignant;
    }
    
    public void setIdenseignant(int idenseignant) {
        this.idenseignant = idenseignant;
    }

    
    @Column(name="nom", length=50)
    public String getNom() {
        return this.nom;
    }
    
    public void setNom(String nom) {
        this.nom = nom;
    }

    
    @Column(name="prenom", length=50)
    public String getPrenom() {
        return this.prenom;
    }
    
    public void setPrenom(String prenom) {
        this.prenom = prenom;
    }

    
    @Column(name="rang", length=50)
    public String getRang() {
        return this.rang;
    }
    
    public void setRang(String rang) {
        this.rang = rang;
    }

    
    @Column(name="civilite", length=50)
    public String getCivilite() {
        return this.civilite;
    }
    
    public void setCivilite(String civilite) {
        this.civilite = civilite;
    }

    
    @Column(name="diplome", length=50)
    public String getDiplome() {
        return this.diplome;
    }
    
    public void setDiplome(String diplome) {
        this.diplome = diplome;
    }

    
    @Column(name="etat", length=50)
    public String getEtat() {
        return this.etat;
    }
    
    public void setEtat(String etat) {
        this.etat = etat;
    }

    
    @Column(name="usrcreate", length=50)
    public String getUsrcreate() {
        return this.usrcreate;
    }
    
    public void setUsrcreate(String usrcreate) {
        this.usrcreate = usrcreate;
    }

    
    @Column(name="userlastupdate", length=50)
    public String getUserlastupdate() {
        return this.userlastupdate;
    }
    
    public void setUserlastupdate(String userlastupdate) {
        this.userlastupdate = userlastupdate;
    }

    
    @Column(name="userdelete", length=50)
    public String getUserdelete() {
        return this.userdelete;
    }
    
    public void setUserdelete(String userdelete) {
        this.userdelete = userdelete;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="enseignant")
    public Set<Enseignantmatiereclasse> getEnseignantmatiereclasses() {
        return this.enseignantmatiereclasses;
    }
    
    public void setEnseignantmatiereclasses(Set<Enseignantmatiereclasse> enseignantmatiereclasses) {
        this.enseignantmatiereclasses = enseignantmatiereclasses;
    }




}


