package com.university.entities;
// Generated 18 juil. 2018 08:25:27 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Etudiant generated by hbm2java
 */
@Entity
@Table(name="etudiant"
    ,schema="public"
)
public class Etudiant  implements java.io.Serializable {


     private int idetudiant;
     private String matricule;
     private String nometudiant;
     private String prenometudiant;
     private Date datenaissance;
     private String adresse;
     private String photo;
     private String etat;
     private String usrcreate;
     private String userlastupdate;
     private String userdelete;
     private Set<Note> notes = new HashSet<Note>(0);
     private Set<Inscription> inscriptions = new HashSet<Inscription>(0);

    public Etudiant() {
    }

	
    public Etudiant(int idetudiant) {
        this.idetudiant = idetudiant;
    }
    public Etudiant(int idetudiant, String matricule, String nometudiant, String prenometudiant, Date datenaissance, String adresse, String photo, String etat, String usrcreate, String userlastupdate, String userdelete, Set<Note> notes, Set<Inscription> inscriptions) {
       this.idetudiant = idetudiant;
       this.matricule = matricule;
       this.nometudiant = nometudiant;
       this.prenometudiant = prenometudiant;
       this.datenaissance = datenaissance;
       this.adresse = adresse;
       this.photo = photo;
       this.etat = etat;
       this.usrcreate = usrcreate;
       this.userlastupdate = userlastupdate;
       this.userdelete = userdelete;
       this.notes = notes;
       this.inscriptions = inscriptions;
    }
   
     @Id 

    
    @Column(name="idetudiant", unique=true, nullable=false)
    public int getIdetudiant() {
        return this.idetudiant;
    }
    
    public void setIdetudiant(int idetudiant) {
        this.idetudiant = idetudiant;
    }

    
    @Column(name="matricule", length=20)
    public String getMatricule() {
        return this.matricule;
    }
    
    public void setMatricule(String matricule) {
        this.matricule = matricule;
    }

    
    @Column(name="nometudiant", length=50)
    public String getNometudiant() {
        return this.nometudiant;
    }
    
    public void setNometudiant(String nometudiant) {
        this.nometudiant = nometudiant;
    }

    
    @Column(name="prenometudiant", length=50)
    public String getPrenometudiant() {
        return this.prenometudiant;
    }
    
    public void setPrenometudiant(String prenometudiant) {
        this.prenometudiant = prenometudiant;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="datenaissance", length=13)
    public Date getDatenaissance() {
        return this.datenaissance;
    }
    
    public void setDatenaissance(Date datenaissance) {
        this.datenaissance = datenaissance;
    }

    
    @Column(name="adresse", length=150)
    public String getAdresse() {
        return this.adresse;
    }
    
    public void setAdresse(String adresse) {
        this.adresse = adresse;
    }

    
    @Column(name="photo", length=50)
    public String getPhoto() {
        return this.photo;
    }
    
    public void setPhoto(String photo) {
        this.photo = photo;
    }

    
    @Column(name="etat", length=20)
    public String getEtat() {
        return this.etat;
    }
    
    public void setEtat(String etat) {
        this.etat = etat;
    }

    
    @Column(name="usrcreate", length=50)
    public String getUsrcreate() {
        return this.usrcreate;
    }
    
    public void setUsrcreate(String usrcreate) {
        this.usrcreate = usrcreate;
    }

    
    @Column(name="userlastupdate", length=50)
    public String getUserlastupdate() {
        return this.userlastupdate;
    }
    
    public void setUserlastupdate(String userlastupdate) {
        this.userlastupdate = userlastupdate;
    }

    
    @Column(name="userdelete", length=50)
    public String getUserdelete() {
        return this.userdelete;
    }
    
    public void setUserdelete(String userdelete) {
        this.userdelete = userdelete;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="etudiant")
    public Set<Note> getNotes() {
        return this.notes;
    }
    
    public void setNotes(Set<Note> notes) {
        this.notes = notes;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="etudiant")
    public Set<Inscription> getInscriptions() {
        return this.inscriptions;
    }
    
    public void setInscriptions(Set<Inscription> inscriptions) {
        this.inscriptions = inscriptions;
    }




}


