package com.university.entities;
// Generated 18 juil. 2018 08:25:27 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Filiere generated by hbm2java
 */
@Entity
@Table(name="filiere"
    ,schema="public"
)
public class Filiere  implements java.io.Serializable {


     private int idfiliere;
     private String libellelongfiliere;
     private String libellecourtfiliere;
     private String usrcreate;
     private String userlastupdate;
     private String userdelete;
     private Set<Classe> classes = new HashSet<Classe>(0);

    public Filiere() {
    }

	
    public Filiere(int idfiliere) {
        this.idfiliere = idfiliere;
    }
    public Filiere(int idfiliere, String libellelongfiliere, String libellecourtfiliere, String usrcreate, String userlastupdate, String userdelete, Set<Classe> classes) {
       this.idfiliere = idfiliere;
       this.libellelongfiliere = libellelongfiliere;
       this.libellecourtfiliere = libellecourtfiliere;
       this.usrcreate = usrcreate;
       this.userlastupdate = userlastupdate;
       this.userdelete = userdelete;
       this.classes = classes;
    }
   
     @Id 

    
    @Column(name="idfiliere", unique=true, nullable=false)
    public int getIdfiliere() {
        return this.idfiliere;
    }
    
    public void setIdfiliere(int idfiliere) {
        this.idfiliere = idfiliere;
    }

    
    @Column(name="libellelongfiliere", length=50)
    public String getLibellelongfiliere() {
        return this.libellelongfiliere;
    }
    
    public void setLibellelongfiliere(String libellelongfiliere) {
        this.libellelongfiliere = libellelongfiliere;
    }

    
    @Column(name="libellecourtfiliere", length=10)
    public String getLibellecourtfiliere() {
        return this.libellecourtfiliere;
    }
    
    public void setLibellecourtfiliere(String libellecourtfiliere) {
        this.libellecourtfiliere = libellecourtfiliere;
    }

    
    @Column(name="usrcreate", length=50)
    public String getUsrcreate() {
        return this.usrcreate;
    }
    
    public void setUsrcreate(String usrcreate) {
        this.usrcreate = usrcreate;
    }

    
    @Column(name="userlastupdate", length=50)
    public String getUserlastupdate() {
        return this.userlastupdate;
    }
    
    public void setUserlastupdate(String userlastupdate) {
        this.userlastupdate = userlastupdate;
    }

    
    @Column(name="userdelete", length=50)
    public String getUserdelete() {
        return this.userdelete;
    }
    
    public void setUserdelete(String userdelete) {
        this.userdelete = userdelete;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="filiere")
    public Set<Classe> getClasses() {
        return this.classes;
    }
    
    public void setClasses(Set<Classe> classes) {
        this.classes = classes;
    }




}


