package com.university.entities;
// Generated 18 juil. 2018 08:25:27 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Inscription generated by hbm2java
 */
@Entity
@Table(name="inscription"
    ,schema="public"
)
public class Inscription  implements java.io.Serializable {


     private int idinscription;
     private Classe classe;
     private Etudiant etudiant;
     private BigDecimal scolarite;
     private Integer montantscolaritepaye;
     private String annee;
     private String usrcreate;
     private String userlastupdate;
     private String userdelete;
     private Set<Detailpaiement> detailpaiements = new HashSet<Detailpaiement>(0);
     private Set<Moyenne> moyennes = new HashSet<Moyenne>(0);
     private Set<Piecejustificative> piecejustificatives = new HashSet<Piecejustificative>(0);

    public Inscription() {
    }

	
    public Inscription(int idinscription) {
        this.idinscription = idinscription;
    }
    public Inscription(int idinscription, Classe classe, Etudiant etudiant, BigDecimal scolarite, Integer montantscolaritepaye, String annee, String usrcreate, String userlastupdate, String userdelete, Set<Detailpaiement> detailpaiements, Set<Moyenne> moyennes, Set<Piecejustificative> piecejustificatives) {
       this.idinscription = idinscription;
       this.classe = classe;
       this.etudiant = etudiant;
       this.scolarite = scolarite;
       this.montantscolaritepaye = montantscolaritepaye;
       this.annee = annee;
       this.usrcreate = usrcreate;
       this.userlastupdate = userlastupdate;
       this.userdelete = userdelete;
       this.detailpaiements = detailpaiements;
       this.moyennes = moyennes;
       this.piecejustificatives = piecejustificatives;
    }
   
     @Id 

    
    @Column(name="idinscription", unique=true, nullable=false)
    public int getIdinscription() {
        return this.idinscription;
    }
    
    public void setIdinscription(int idinscription) {
        this.idinscription = idinscription;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idclasse")
    public Classe getClasse() {
        return this.classe;
    }
    
    public void setClasse(Classe classe) {
        this.classe = classe;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idetudiant")
    public Etudiant getEtudiant() {
        return this.etudiant;
    }
    
    public void setEtudiant(Etudiant etudiant) {
        this.etudiant = etudiant;
    }

    
    @Column(name="scolarite", precision=131089, scale=0)
    public BigDecimal getScolarite() {
        return this.scolarite;
    }
    
    public void setScolarite(BigDecimal scolarite) {
        this.scolarite = scolarite;
    }

    
    @Column(name="montantscolaritepaye")
    public Integer getMontantscolaritepaye() {
        return this.montantscolaritepaye;
    }
    
    public void setMontantscolaritepaye(Integer montantscolaritepaye) {
        this.montantscolaritepaye = montantscolaritepaye;
    }

    
    @Column(name="annee", length=20)
    public String getAnnee() {
        return this.annee;
    }
    
    public void setAnnee(String annee) {
        this.annee = annee;
    }

    
    @Column(name="usrcreate", length=50)
    public String getUsrcreate() {
        return this.usrcreate;
    }
    
    public void setUsrcreate(String usrcreate) {
        this.usrcreate = usrcreate;
    }

    
    @Column(name="userlastupdate", length=50)
    public String getUserlastupdate() {
        return this.userlastupdate;
    }
    
    public void setUserlastupdate(String userlastupdate) {
        this.userlastupdate = userlastupdate;
    }

    
    @Column(name="userdelete", length=50)
    public String getUserdelete() {
        return this.userdelete;
    }
    
    public void setUserdelete(String userdelete) {
        this.userdelete = userdelete;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="inscription")
    public Set<Detailpaiement> getDetailpaiements() {
        return this.detailpaiements;
    }
    
    public void setDetailpaiements(Set<Detailpaiement> detailpaiements) {
        this.detailpaiements = detailpaiements;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="inscription")
    public Set<Moyenne> getMoyennes() {
        return this.moyennes;
    }
    
    public void setMoyennes(Set<Moyenne> moyennes) {
        this.moyennes = moyennes;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="inscription")
    public Set<Piecejustificative> getPiecejustificatives() {
        return this.piecejustificatives;
    }
    
    public void setPiecejustificatives(Set<Piecejustificative> piecejustificatives) {
        this.piecejustificatives = piecejustificatives;
    }




}


