package com.university.entities;
// Generated 18 juil. 2018 08:25:27 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Matiere generated by hbm2java
 */
@Entity
@Table(name="matiere"
    ,schema="public"
)
public class Matiere  implements java.io.Serializable {


     private int idmatiere;
     private String codematiere;
     private String libellelongmatiere;
     private Integer libellecourtmatiere;
     private String etat;
     private String usrcreate;
     private String userlastupdate;
     private String userdelete;
     private Set<Note> notes = new HashSet<Note>(0);
     private Set<Enseignantmatiereclasse> enseignantmatiereclasses = new HashSet<Enseignantmatiereclasse>(0);

    public Matiere() {
    }

	
    public Matiere(int idmatiere) {
        this.idmatiere = idmatiere;
    }
    public Matiere(int idmatiere, String codematiere, String libellelongmatiere, Integer libellecourtmatiere, String etat, String usrcreate, String userlastupdate, String userdelete, Set<Note> notes, Set<Enseignantmatiereclasse> enseignantmatiereclasses) {
       this.idmatiere = idmatiere;
       this.codematiere = codematiere;
       this.libellelongmatiere = libellelongmatiere;
       this.libellecourtmatiere = libellecourtmatiere;
       this.etat = etat;
       this.usrcreate = usrcreate;
       this.userlastupdate = userlastupdate;
       this.userdelete = userdelete;
       this.notes = notes;
       this.enseignantmatiereclasses = enseignantmatiereclasses;
    }
   
     @Id 

    
    @Column(name="idmatiere", unique=true, nullable=false)
    public int getIdmatiere() {
        return this.idmatiere;
    }
    
    public void setIdmatiere(int idmatiere) {
        this.idmatiere = idmatiere;
    }

    
    @Column(name="codematiere", length=20)
    public String getCodematiere() {
        return this.codematiere;
    }
    
    public void setCodematiere(String codematiere) {
        this.codematiere = codematiere;
    }

    
    @Column(name="libellelongmatiere", length=100)
    public String getLibellelongmatiere() {
        return this.libellelongmatiere;
    }
    
    public void setLibellelongmatiere(String libellelongmatiere) {
        this.libellelongmatiere = libellelongmatiere;
    }

    
    @Column(name="libellecourtmatiere")
    public Integer getLibellecourtmatiere() {
        return this.libellecourtmatiere;
    }
    
    public void setLibellecourtmatiere(Integer libellecourtmatiere) {
        this.libellecourtmatiere = libellecourtmatiere;
    }

    
    @Column(name="etat", length=20)
    public String getEtat() {
        return this.etat;
    }
    
    public void setEtat(String etat) {
        this.etat = etat;
    }

    
    @Column(name="usrcreate", length=50)
    public String getUsrcreate() {
        return this.usrcreate;
    }
    
    public void setUsrcreate(String usrcreate) {
        this.usrcreate = usrcreate;
    }

    
    @Column(name="userlastupdate", length=50)
    public String getUserlastupdate() {
        return this.userlastupdate;
    }
    
    public void setUserlastupdate(String userlastupdate) {
        this.userlastupdate = userlastupdate;
    }

    
    @Column(name="userdelete", length=50)
    public String getUserdelete() {
        return this.userdelete;
    }
    
    public void setUserdelete(String userdelete) {
        this.userdelete = userdelete;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="matiere")
    public Set<Note> getNotes() {
        return this.notes;
    }
    
    public void setNotes(Set<Note> notes) {
        this.notes = notes;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="matiere")
    public Set<Enseignantmatiereclasse> getEnseignantmatiereclasses() {
        return this.enseignantmatiereclasses;
    }
    
    public void setEnseignantmatiereclasses(Set<Enseignantmatiereclasse> enseignantmatiereclasses) {
        this.enseignantmatiereclasses = enseignantmatiereclasses;
    }




}


