package com.university.entities;
// Generated 18 juil. 2018 08:25:27 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Moyenne generated by hbm2java
 */
@Entity
@Table(name="moyenne"
    ,schema="public"
)
public class Moyenne  implements java.io.Serializable {


     private int idmoyenne;
     private Inscription inscription;
     private BigDecimal moyenne;
     private Boolean fgsession;
     private Integer semestre;
     private String usrcreate;
     private String userlastupdate;
     private String userdelete;

    public Moyenne() {
    }

	
    public Moyenne(int idmoyenne) {
        this.idmoyenne = idmoyenne;
    }
    public Moyenne(int idmoyenne, Inscription inscription, BigDecimal moyenne, Boolean fgsession, Integer semestre, String usrcreate, String userlastupdate, String userdelete) {
       this.idmoyenne = idmoyenne;
       this.inscription = inscription;
       this.moyenne = moyenne;
       this.fgsession = fgsession;
       this.semestre = semestre;
       this.usrcreate = usrcreate;
       this.userlastupdate = userlastupdate;
       this.userdelete = userdelete;
    }
   
     @Id 

    
    @Column(name="idmoyenne", unique=true, nullable=false)
    public int getIdmoyenne() {
        return this.idmoyenne;
    }
    
    public void setIdmoyenne(int idmoyenne) {
        this.idmoyenne = idmoyenne;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idinscription")
    public Inscription getInscription() {
        return this.inscription;
    }
    
    public void setInscription(Inscription inscription) {
        this.inscription = inscription;
    }

    
    @Column(name="moyenne", precision=131089, scale=0)
    public BigDecimal getMoyenne() {
        return this.moyenne;
    }
    
    public void setMoyenne(BigDecimal moyenne) {
        this.moyenne = moyenne;
    }

    
    @Column(name="fgsession")
    public Boolean getFgsession() {
        return this.fgsession;
    }
    
    public void setFgsession(Boolean fgsession) {
        this.fgsession = fgsession;
    }

    
    @Column(name="semestre")
    public Integer getSemestre() {
        return this.semestre;
    }
    
    public void setSemestre(Integer semestre) {
        this.semestre = semestre;
    }

    
    @Column(name="usrcreate", length=50)
    public String getUsrcreate() {
        return this.usrcreate;
    }
    
    public void setUsrcreate(String usrcreate) {
        this.usrcreate = usrcreate;
    }

    
    @Column(name="userlastupdate", length=50)
    public String getUserlastupdate() {
        return this.userlastupdate;
    }
    
    public void setUserlastupdate(String userlastupdate) {
        this.userlastupdate = userlastupdate;
    }

    
    @Column(name="userdelete", length=50)
    public String getUserdelete() {
        return this.userdelete;
    }
    
    public void setUserdelete(String userdelete) {
        this.userdelete = userdelete;
    }




}


