package com.university.entities;
// Generated 18 juil. 2018 08:25:27 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Note generated by hbm2java
 */
@Entity
@Table(name="note"
    ,schema="public"
)
public class Note  implements java.io.Serializable {


     private int idnote;
     private Etudiant etudiant;
     private Matiere matiere;
     private Integer note;
     private Integer noterattrapage;
     private Integer semestre;
     private String annee;
     private String etat;
     private String usrcreate;
     private String userlastupdate;
     private String userdelete;

    public Note() {
    }

	
    public Note(int idnote) {
        this.idnote = idnote;
    }
    public Note(int idnote, Etudiant etudiant, Matiere matiere, Integer note, Integer noterattrapage, Integer semestre, String annee, String etat, String usrcreate, String userlastupdate, String userdelete) {
       this.idnote = idnote;
       this.etudiant = etudiant;
       this.matiere = matiere;
       this.note = note;
       this.noterattrapage = noterattrapage;
       this.semestre = semestre;
       this.annee = annee;
       this.etat = etat;
       this.usrcreate = usrcreate;
       this.userlastupdate = userlastupdate;
       this.userdelete = userdelete;
    }
   
     @Id 

    
    @Column(name="idnote", unique=true, nullable=false)
    public int getIdnote() {
        return this.idnote;
    }
    
    public void setIdnote(int idnote) {
        this.idnote = idnote;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idetudiant")
    public Etudiant getEtudiant() {
        return this.etudiant;
    }
    
    public void setEtudiant(Etudiant etudiant) {
        this.etudiant = etudiant;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idmatiere")
    public Matiere getMatiere() {
        return this.matiere;
    }
    
    public void setMatiere(Matiere matiere) {
        this.matiere = matiere;
    }

    
    @Column(name="note")
    public Integer getNote() {
        return this.note;
    }
    
    public void setNote(Integer note) {
        this.note = note;
    }

    
    @Column(name="noterattrapage")
    public Integer getNoterattrapage() {
        return this.noterattrapage;
    }
    
    public void setNoterattrapage(Integer noterattrapage) {
        this.noterattrapage = noterattrapage;
    }

    
    @Column(name="semestre")
    public Integer getSemestre() {
        return this.semestre;
    }
    
    public void setSemestre(Integer semestre) {
        this.semestre = semestre;
    }

    
    @Column(name="annee", length=20)
    public String getAnnee() {
        return this.annee;
    }
    
    public void setAnnee(String annee) {
        this.annee = annee;
    }

    
    @Column(name="etat", length=20)
    public String getEtat() {
        return this.etat;
    }
    
    public void setEtat(String etat) {
        this.etat = etat;
    }

    
    @Column(name="usrcreate", length=50)
    public String getUsrcreate() {
        return this.usrcreate;
    }
    
    public void setUsrcreate(String usrcreate) {
        this.usrcreate = usrcreate;
    }

    
    @Column(name="userlastupdate", length=50)
    public String getUserlastupdate() {
        return this.userlastupdate;
    }
    
    public void setUserlastupdate(String userlastupdate) {
        this.userlastupdate = userlastupdate;
    }

    
    @Column(name="userdelete", length=50)
    public String getUserdelete() {
        return this.userdelete;
    }
    
    public void setUserdelete(String userdelete) {
        this.userdelete = userdelete;
    }




}


