package com.university.entities;
// Generated 18 juil. 2018 08:25:27 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Piecejustificative generated by hbm2java
 */
@Entity
@Table(name="piecejustificative"
    ,schema="public"
)
public class Piecejustificative  implements java.io.Serializable {


     private int idpiecejustificative;
     private Inscription inscription;
     private String nompiecejustificative;
     private Integer path;
     private String etat;
     private String usercreate;
     private String userlastupdate;
     private String userdelete;

    public Piecejustificative() {
    }

	
    public Piecejustificative(int idpiecejustificative) {
        this.idpiecejustificative = idpiecejustificative;
    }
    public Piecejustificative(int idpiecejustificative, Inscription inscription, String nompiecejustificative, Integer path, String etat, String usercreate, String userlastupdate, String userdelete) {
       this.idpiecejustificative = idpiecejustificative;
       this.inscription = inscription;
       this.nompiecejustificative = nompiecejustificative;
       this.path = path;
       this.etat = etat;
       this.usercreate = usercreate;
       this.userlastupdate = userlastupdate;
       this.userdelete = userdelete;
    }
   
     @Id 

    
    @Column(name="idpiecejustificative", unique=true, nullable=false)
    public int getIdpiecejustificative() {
        return this.idpiecejustificative;
    }
    
    public void setIdpiecejustificative(int idpiecejustificative) {
        this.idpiecejustificative = idpiecejustificative;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idinscription")
    public Inscription getInscription() {
        return this.inscription;
    }
    
    public void setInscription(Inscription inscription) {
        this.inscription = inscription;
    }

    
    @Column(name="nompiecejustificative", length=100)
    public String getNompiecejustificative() {
        return this.nompiecejustificative;
    }
    
    public void setNompiecejustificative(String nompiecejustificative) {
        this.nompiecejustificative = nompiecejustificative;
    }

    
    @Column(name="path")
    public Integer getPath() {
        return this.path;
    }
    
    public void setPath(Integer path) {
        this.path = path;
    }

    
    @Column(name="etat", length=20)
    public String getEtat() {
        return this.etat;
    }
    
    public void setEtat(String etat) {
        this.etat = etat;
    }

    
    @Column(name="usercreate", length=50)
    public String getUsercreate() {
        return this.usercreate;
    }
    
    public void setUsercreate(String usercreate) {
        this.usercreate = usercreate;
    }

    
    @Column(name="userlastupdate", length=50)
    public String getUserlastupdate() {
        return this.userlastupdate;
    }
    
    public void setUserlastupdate(String userlastupdate) {
        this.userlastupdate = userlastupdate;
    }

    
    @Column(name="userdelete", length=50)
    public String getUserdelete() {
        return this.userdelete;
    }
    
    public void setUserdelete(String userdelete) {
        this.userdelete = userdelete;
    }




}


