package com.university.entities;
// Generated 18 juil. 2018 08:25:27 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Uniteenseignement generated by hbm2java
 */
@Entity
@Table(name="uniteenseignement"
    ,schema="public"
)
public class Uniteenseignement  implements java.io.Serializable {


     private int idue;
     private String libelleue;
     private String usrcreate;
     private String userlastupdate;
     private String userdelete;
     private Set<Enseignantmatiereclasse> enseignantmatiereclasses = new HashSet<Enseignantmatiereclasse>(0);

    public Uniteenseignement() {
    }

	
    public Uniteenseignement(int idue) {
        this.idue = idue;
    }
    public Uniteenseignement(int idue, String libelleue, String usrcreate, String userlastupdate, String userdelete, Set<Enseignantmatiereclasse> enseignantmatiereclasses) {
       this.idue = idue;
       this.libelleue = libelleue;
       this.usrcreate = usrcreate;
       this.userlastupdate = userlastupdate;
       this.userdelete = userdelete;
       this.enseignantmatiereclasses = enseignantmatiereclasses;
    }
   
     @Id 

    
    @Column(name="idue", unique=true, nullable=false)
    public int getIdue() {
        return this.idue;
    }
    
    public void setIdue(int idue) {
        this.idue = idue;
    }

    
    @Column(name="libelleue", length=20)
    public String getLibelleue() {
        return this.libelleue;
    }
    
    public void setLibelleue(String libelleue) {
        this.libelleue = libelleue;
    }

    
    @Column(name="usrcreate", length=50)
    public String getUsrcreate() {
        return this.usrcreate;
    }
    
    public void setUsrcreate(String usrcreate) {
        this.usrcreate = usrcreate;
    }

    
    @Column(name="userlastupdate", length=50)
    public String getUserlastupdate() {
        return this.userlastupdate;
    }
    
    public void setUserlastupdate(String userlastupdate) {
        this.userlastupdate = userlastupdate;
    }

    
    @Column(name="userdelete", length=50)
    public String getUserdelete() {
        return this.userdelete;
    }
    
    public void setUserdelete(String userdelete) {
        this.userdelete = userdelete;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="uniteenseignement")
    public Set<Enseignantmatiereclasse> getEnseignantmatiereclasses() {
        return this.enseignantmatiereclasses;
    }
    
    public void setEnseignantmatiereclasses(Set<Enseignantmatiereclasse> enseignantmatiereclasses) {
        this.enseignantmatiereclasses = enseignantmatiereclasses;
    }




}


